- id.go
- id_test.go
Get the process id just once instead of every time we generate an ID. Without this change an id generation takes `159ns`, after this change this is just `27ns`.
I've also added an benchark to this pull request. So you can verify it yourself. Compared to many other id libraries, xid is crazy fast after this change.
> get pid only once

- id.go
- id_test.go
text should not be altered as it can cause unmarshaling synchronization errors.
> Copy text when unmarshaling to avoid sync errors

- id.go
- id_test.go
In case of MySQL and go-sql-driver/mysql(https://github.com/go-sql-driver/mysql), Scan receive the value of `[]byte`.
> Fixed `sql.Scanner.Scan`if it received []byte value from some database

- README.md
Hi,
I'd like to add a link to a Scala port of xid in case someone is interested in this library on the JVM side. Given that there already has been a question about that by @on99
Thanks.
> Add a Scala implementation to docs

- go.mod
add a go.mod file so as to prepare for vgo; https://github.com/golang/vgo
But the main reason I added this PR is so as to ask the maintainer to properly semver tag this repository. 
right now `github.com/rs/xid` has git tags like`v1.0` `v1.1` 
If you have `github.com/rs/xid` as a dependency on your app and you use vgo as dependency manager; it is generating a `go.mod` file like;
```bash
module github/komuw/myModule
require (
github.com/rs/xid v0.0.0-20170604230408-02dd45c33376
github.com/rs/zerolog v1.4.0
)
```
instead of picking xid tag v1.1 
So my proposal is that, this project should add a new semver tag like; v1.1.0
> add go.mod file

- id.go
I'm are using xid's ability to sort by creation date. I had existing data that needed to be migrated to use xid. To get the sort to work with this historic data I needed a way to be able to specify the date used when creating a new xid. 
I'm happy to make any requested changes like using a different function name.
Many thanks for maintaining the xid project, I use it all the time. 
Sam
> Allow for specifying the time to be used when creating a new xid

- go.mod
- id.go
Hi, I patched 2 fixes for performance improvement.
1. It is possible to skip the subsequent boundary value check by accessing from the end of the slice, so I changed it.  ( https://go101.org/article/bounds-check-elimination.html#slice-comparison )
2. zero copy casting like strings.Builder. ( https://golang.org/src/strings/builder.go?s=1416:1457#L36 )
Signed-off-by: kpango <i.can.feel.gravity@gmail.com>
> [patch] improve performance

- id.go
As per title, 1 alloc within MarshalJSON can be avoided at the cost of a tiny bit of duplication.
benchmark                  old ns/op     new ns/op     delta
BenchmarkMarshalJSON-8     45.1          32.0          -29.05%
benchmark                  old allocs    new allocs    delta
BenchmarkMarshalJSON-8     2             1             -50.00%
benchmark                  old bytes     new bytes     delta
BenchmarkMarshalJSON-8     64            32            -50.00%
> Avoid unnecessary alloc in MarshalJSON

- id.go
- id_test.go
xid is wonderful for tracing, it would be nice to add a `Encode` method, enabling us to write zero allocation servers. Thanks.
Signed-off-by: phuslu <phus.lu@gmail.com>
> add Encode method for memory sensitive cases

- README.md
Hi,
I'd like to add a link to a pure Java port of `xid`. 
Thanks.
> Add a Java implementation to docs

- hostid_linux.go
read "/sys/class/dmi/id/product_uuid" requires root permission, so we could try "/etc/machine-id" at first.
[1] https://man7.org/linux/man-pages/man5/machine-id.5.html
> Try /etc/machine-id for linux first

- id.go
- id_test.go
Unmarshalling of one-digit integers causes panic.
```
panic: runtime error: slice bounds out of range [1:0]
```
> Fix panic on unmarshalling JSON

- README.md
I would like to add a link to the dart port of this library
> Add link to dart port

- id.go
- id_test.go
Refer: #71  #75 
old:
```
go test -bench 'FromString*' -benchmem
goos: darwin
goarch: arm64
pkg: github.com/rs/xid
BenchmarkFromString-10    	445015340	         2.618 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/rs/xid	1.807s
```
new:
```
go test -bench 'FromString*' -benchmem
goos: darwin
goarch: arm64
pkg: github.com/rs/xid
BenchmarkFromString-10    	521384266	         2.304 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/rs/xid	1.556s
```
> Just need to check the last byte.

- id.go
Some libraries (e.g. JSON marshalers together with `omitempty` struct flags) support `IsZero()` for skipping empty values.
> Added `IsZero()`, alias of `IsNil()`

- id.go
While object ID generation doesn't rely on the cryptographic security of MD5, many [FIPS](https://csrc.nist.gov/publications/detail/fips/140/2/final) environments block the use of MD5 entirely. Mongo has also moved away from MD5 in their implementations of object ID generation for the same reason [1]. They initially replaced MD5 with FNV-1a, but the C driver at least has since moved from FNV-1a to SipHash.
In any case, the machine ID is generated only once during initialization in this code, so the speed of the chosen hash function is not important.
[1] https://jira.mongodb.org/browse/DRIVERS-492
> Generate machine ID using SHA-256 to avoid FIPS compliance issues

- README.md
I believe there is a mistake in the second paragraph (when base64 is mentioned). I fixed it and provided more context around base32hex
> clarified used encoding --> base32hex

- .github/workflows/go.yml
- .gitignore
- go.mod
- hostid_darwin.go
- hostid_windows.go
- Addresses #100 based on fix suggested by @rpendleton
- Adds multi-platform matrix run strategy to actions
- Adds .gitignore file
- Address #78
> Fix UUID for Darwin hosts

- hostid_linux.go
- id.go
The `ioutil` package was deprecated with the [release of Go 1.16](https://go.dev/doc/go1.16#ioutil).
I've removed calls to the old package and replaced them with their counterparts. There shouldn't be any change in behaviour, as I think the calls were internally mapped already.
This does remove some annoying LSP warnings though.
> Remove calls to deprecated `ioutil` package.

- README.md
- id.go
- id_test.go
To go along with my suggestion in https://github.com/rs/xid/issues/112, this simple addition would solve some edge cases I've been seeing, and wouldn't change default behavior for generating ids.
> Allow MachineID to be set
